import { ArrowDownToLine, ArrowUpFromLine, Boxes, CircleAlert, PackageCheck, PackageX, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useStock } from '../store/StockContext'
import { StatusBadge, TxBadge } from '../components/ui'

export function DashboardPage(){const {items,categories,locations,transactions,loading}=useStock();const low=items.filter(i=>i.quantity>0&&i.quantity<=i.minStock);const out=items.filter(i=>i.quantity===0);const total=items.reduce((s,i)=>s+i.quantity,0);const todayOut=transactions.filter(t=>t.type==='OUT'&&t.createdAt.startsWith('2026-09-22')).reduce((s,t)=>s+t.quantity,0)
 const cards=[['รายการทั้งหมด',items.length,'รายการ',Boxes,'navy'],['จำนวนคงเหลือ',total,'หน่วย',PackageCheck,'teal'],['สินค้าใกล้หมด',low.length,'รายการ',CircleAlert,'amber'],['สินค้าหมด',out.length,'รายการ',PackageX,'red'],['เบิกออกวันนี้',todayOut,'หน่วย',ArrowUpFromLine,'blue']] as const
 return <div className="page-stack"><section className="metric-grid">{cards.map(([label,value,unit,Icon,tone])=><article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={22}/></div><div><span>{label}</span><strong>{loading?'—':value.toLocaleString('th-TH')} <small>{unit}</small></strong></div></article>)}</section>
 <div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><h2>แจ้งเตือนสินค้าใกล้หมด</h2><p>รายการที่ควรสั่งซื้อหรือเติมสต็อก</p></div><Link to="/low-stock">ดูทั้งหมด</Link></div><div className="table-wrap"><table><thead><tr><th>สินค้า</th><th>รหัส</th><th>คงเหลือ</th><th>ขั้นต่ำ</th><th>สถานะ</th></tr></thead><tbody>{[...out,...low].slice(0,5).map(i=><tr key={i.id}><td><b>{i.name}</b></td><td className="mono">{i.sku}</td><td><b>{i.quantity}</b> {i.unit}</td><td>{i.minStock} {i.unit}</td><td><StatusBadge item={i}/></td></tr>)}</tbody></table></div></section>
 <section className="card category-card"><div className="card-head"><div><h2>สต็อกตามหมวดหมู่</h2><p>สัดส่วนจำนวนคงเหลือ</p></div></div><div className="category-bars">{categories.map((c,n)=>{const amount=items.filter(i=>i.categoryId===c.id).reduce((s,i)=>s+i.quantity,0);const pct=Math.max(5,Math.round(amount/Math.max(total,1)*100));return <div key={c.id}><div><span><i className={`dot d${n}`}/>{c.name}</span><b>{amount}</b></div><div className="bar"><i className={`fill d${n}`} style={{width:`${pct}%`}}/></div></div>})}</div><div className="stock-note"><TrendingUp size={17}/><span>วัสดุสำนักงานมีสต็อกสูงสุดในขณะนี้</span></div></section>
 </div><section className="card"><div className="card-head"><div><h2>ความเคลื่อนไหวล่าสุด</h2><p>รายการรับเข้า เบิกออก และปรับยอดล่าสุด</p></div><Link to="/history">ดูประวัติทั้งหมด</Link></div><div className="table-wrap"><table><thead><tr><th>วันและเวลา</th><th>สินค้า</th><th>รายการ</th><th>จำนวน</th><th>ผู้ดำเนินการ</th><th>ตำแหน่ง</th></tr></thead><tbody>{transactions.slice(0,5).map(t=>{const i=items.find(x=>x.id===t.itemId);return <tr key={t.id}><td>{new Intl.DateTimeFormat('th-TH',{dateStyle:'short',timeStyle:'short'}).format(new Date(t.createdAt))}</td><td><b>{i?.name}</b></td><td><TxBadge type={t.type}/></td><td className={t.type==='IN'?'positive':'negative'}>{t.type==='IN'?'+':'−'}{t.quantity} {i?.unit}</td><td>{t.user}</td><td>{locations.find(x=>x.id===t.locationId)?.name}</td></tr>})}</tbody></table></div></section>
 <div className="quick-actions"><Link to="/stock-in"><ArrowDownToLine/>รับสินค้าเข้า</Link><Link to="/stock-out"><ArrowUpFromLine/>เบิกสินค้าออก</Link></div></div>}
