import { Download, MoreHorizontal, PackagePlus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Empty, Modal, StatusBadge, Toast, stockStatus } from '../components/ui'
import { useStock } from '../store/StockContext'
import type { Item } from '../types'

const emptyForm={sku:'',name:'',description:'',categoryId:'',unit:'ชิ้น',minStock:5,barcode:'',isActive:true,locationId:'',imageUrl:''}
export function InventoryPage(){const {items,categories,locations,addItem,updateItem,deleteItem}=useStock();const [q,setQ]=useState('');const [cat,setCat]=useState('');const [loc,setLoc]=useState('');const [status,setStatus]=useState('');const [form,setForm]=useState<typeof emptyForm&{id?:string}>(emptyForm);const [modal,setModal]=useState(false);const [toast,setToast]=useState('');const [page,setPage]=useState(1)
 const filtered=useMemo(()=>items.filter(i=>(i.name+i.sku).toLowerCase().includes(q.toLowerCase())&&(!cat||i.categoryId===cat)&&(!loc||i.locationId===loc)&&(!status||stockStatus(i)===status)),[items,q,cat,loc,status]);const pages=Math.max(1,Math.ceil(filtered.length/7));const shown=filtered.slice((page-1)*7,page*7)
 const open=(item?:Item)=>{setForm(item?{...item,imageUrl:item.imageUrl??''}:emptyForm);setModal(true)};const save=()=>{if(!form.sku||!form.name||!form.categoryId||!form.locationId){setToast('กรุณากรอกข้อมูลที่จำเป็นให้ครบ');return} if(form.id){const old=items.find(i=>i.id===form.id)!;updateItem({...old,...form})}else addItem(form);setModal(false);setToast(form.id?'แก้ไขรายการแล้ว':'เพิ่มรายการใหม่แล้ว');setTimeout(()=>setToast(''),2500)}
 const exportCsv=()=>{const body=['SKU,ชื่อสินค้า,จำนวน,หน่วย',...filtered.map(i=>`${i.sku},${i.name},${i.quantity},${i.unit}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+body],{type:'text/csv'}));a.download='inventory.csv';a.click()}
 return <div className="page-stack"><div className="page-actions"><div className="search"><Search size={18}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="ค้นหาชื่อหรือรหัสสินค้า"/></div><div className="action-buttons"><button className="btn secondary" onClick={exportCsv}><Download size={18}/>ส่งออก</button><button className="btn primary" onClick={()=>open()}><PackagePlus size={18}/>เพิ่มสินค้า</button></div></div>
 <section className="filters"><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">ทุกหมวดหมู่</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select value={loc} onChange={e=>setLoc(e.target.value)}><option value="">ทุกตำแหน่ง</option>{locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทุกสถานะ</option><option>ปกติ</option><option>ใกล้หมด</option><option>หมด</option></select><span>พบ {filtered.length} รายการ</span></section>
 <section className="card inventory-card"><div className="table-wrap"><table><thead><tr><th>สินค้า</th><th>รหัส</th><th>ชื่อสินค้า</th><th>หมวดหมู่</th><th>ตำแหน่ง</th><th>คงเหลือ</th><th>ขั้นต่ำ</th><th>สถานะ</th><th/></tr></thead><tbody>{shown.map(i=><tr key={i.id}><td><div className="product-icon">{i.name.charAt(0)}</div></td><td className="mono">{i.sku}</td><td><Link to={`/inventory/${i.id}`}><b>{i.name}</b></Link><small>{i.description}</small></td><td>{categories.find(c=>c.id===i.categoryId)?.name}</td><td>{locations.find(l=>l.id===i.locationId)?.name}</td><td><b className="quantity">{i.quantity}</b> {i.unit}</td><td>{i.minStock} {i.unit}</td><td><StatusBadge item={i}/></td><td><details className="row-menu"><summary><MoreHorizontal/></summary><div><Link to={`/inventory/${i.id}`}>ดูรายละเอียด</Link><button onClick={()=>open(i)}>แก้ไข</button><Link to={`/stock-in?item=${i.id}`}>รับเข้า</Link><Link to={`/stock-out?item=${i.id}`}>เบิกออก</Link><button className="danger-text" onClick={()=>deleteItem(i.id)}>ลบ</button></div></details></td></tr>)}</tbody></table>{!shown.length&&<Empty text="ไม่พบสินค้าที่ตรงกับเงื่อนไข"/>}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</button><span>หน้า {page} จาก {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>ถัดไป</button></div></section>
 {modal&&<Modal title={form.id?'แก้ไขสินค้า':'เพิ่มสินค้าใหม่'} onClose={()=>setModal(false)}><div className="modal-body form-grid"><label>รหัสสินค้า *<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>ชื่อสินค้า *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="full">รายละเอียด<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>หมวดหมู่ *<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">เลือกหมวดหมู่</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>หน่วยนับ *<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>สต็อกขั้นต่ำ *<input type="number" min="0" value={form.minStock} onChange={e=>setForm({...form,minStock:Number(e.target.value)})}/></label><label>ตำแหน่ง *<select value={form.locationId} onChange={e=>setForm({...form,locationId:e.target.value})}><option value="">เลือกตำแหน่ง</option>{locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label>บาร์โค้ด / QR Code<input value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label>รูปสินค้า<input type="file" accept="image/*"/></label><label className="switch-line full"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>เปิดใช้งานรายการนี้</label></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setModal(false)}>ยกเลิก</button><button className="btn primary" onClick={save}>บันทึก</button></div></Modal>}{toast&&<Toast message={toast}/>}</div>}
