import { CheckCircle2, Clock3, PackagePlus, Plus, Send, Trash2, XCircle } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Confirm, Empty, Modal, Toast } from '../components/ui'
import { DEPARTMENTS } from '../constants/departments'
import { useAuth } from '../store/AuthContext'
import { useIssueRequests } from '../store/IssueRequestContext'
import { useStock } from '../store/StockContext'
import type { IssueRequest, IssueRequestStatus } from '../types'
import { formatThaiDateTime } from '../utils/date'

const statusLabel:Record<IssueRequestStatus,string>={PENDING:'รออนุมัติ',APPROVED:'อนุมัติแล้ว',REJECTED:'ไม่อนุมัติ',CANCELLED:'ยกเลิก'}
const statusIcon:Record<IssueRequestStatus,typeof Clock3>={PENDING:Clock3,APPROVED:CheckCircle2,REJECTED:XCircle,CANCELLED:XCircle}
type DraftLine={key:string;itemId:string;locationId:string;quantity:number}
const blankLine=():DraftLine=>({key:crypto.randomUUID(),itemId:'',locationId:'',quantity:1})

function RequestCard({request,operator,onApprove,onReject,onCancel}:{request:IssueRequest;operator:boolean;onApprove?:(request:IssueRequest)=>void;onReject?:(request:IssueRequest)=>void;onCancel?:(request:IssueRequest)=>void}){
 const Icon=statusIcon[request.status];const short=request.lines.some(line=>line.quantity>line.availableQuantity)
 return <article className="issue-request-card">
  <header><div><span className={`issue-request-status ${request.status.toLowerCase()}`}><Icon size={15}/>{statusLabel[request.status]}</span><h3>{request.requestNo}</h3><p>{formatThaiDateTime(request.createdAt)} · ผู้ขอ {request.requestedByName}</p></div>{request.status==='PENDING'&&operator&&<div className="row-actions"><button className="btn compact secondary" onClick={()=>onReject?.(request)}><XCircle size={16}/>ไม่อนุมัติ</button><button className="btn compact primary" disabled={short} onClick={()=>onApprove?.(request)}><CheckCircle2 size={16}/>อนุมัติ</button></div>}{request.status==='PENDING'&&!operator&&<button className="btn compact secondary" onClick={()=>onCancel?.(request)}>ยกเลิกคำขอ</button>}</header>
  <div className="issue-request-meta"><span><b>ผู้รับ:</b> {request.recipientName}</span><span><b>แผนก:</b> {request.department}</span>{request.reviewedByName&&<span><b>ผู้ตรวจสอบ:</b> {request.reviewedByName}</span>}</div>
  <div className="table-wrap"><table><thead><tr><th>สินค้า</th><th>ตำแหน่ง</th><th>จำนวนขอเบิก</th>{request.status==='PENDING'&&operator&&<th>คงเหลือปัจจุบัน</th>}</tr></thead><tbody>{request.lines.map(line=><tr key={line.id}><td><b>{line.itemName}</b><small className="cell-subtitle">{line.sku}</small></td><td>{line.locationName}</td><td>{line.quantity} {line.unit}</td>{request.status==='PENDING'&&operator&&<td className={line.quantity>line.availableQuantity?'negative':''}>{line.availableQuantity} {line.unit}</td>}</tr>)}</tbody></table></div>
  {short&&request.status==='PENDING'&&operator&&<p className="form-error">สต็อกไม่พออย่างน้อยหนึ่งรายการ จึงยังอนุมัติไม่ได้</p>}
  {request.note&&<p className="issue-request-note"><b>หมายเหตุ:</b> {request.note}</p>}
  {request.rejectionReason&&<p className="issue-request-rejection"><b>เหตุผลที่ไม่อนุมัติ:</b> {request.rejectionReason}</p>}
 </article>
}

export function IssueRequestsPage({view='create'}:{view?:'create'|'history'}){
 const {user}=useAuth();const operator=user?.role==='admin'||user?.role==='staff'
 const {items,locations,getLocationQuantity}=useStock();const {requests,pending,loading,create,review,cancel}=useIssueRequests()
 const [recipientName,setRecipientName]=useState(user?.name??'');const [department,setDepartment]=useState('');const [note,setNote]=useState('');const [lines,setLines]=useState<DraftLine[]>([blankLine()])
 const [saving,setSaving]=useState(false);const [toast,setToast]=useState('');const [approveRequest,setApproveRequest]=useState<IssueRequest|null>(null);const [rejectRequest,setRejectRequest]=useState<IssueRequest|null>(null);const [rejectReason,setRejectReason]=useState('')
 const activeItems=items.filter(item=>item.isActive&&item.quantity>0)
 const history=requests.filter(row=>row.status!=='PENDING')
 const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),3000)}
 const updateLine=(key:string,patch:Partial<DraftLine>)=>setLines(current=>current.map(line=>line.key===key?{...line,...patch}:line))
 const selectItem=(line:DraftLine,itemId:string)=>{const item=items.find(row=>row.id===itemId);const available=locations.filter(location=>getLocationQuantity(itemId,location.id)>0).sort((left,right)=>getLocationQuantity(itemId,right.id)-getLocationQuantity(itemId,left.id)||(left.id===item?.locationId?-1:right.id===item?.locationId?1:0));updateLine(line.key,{itemId,locationId:available[0]?.id??'',quantity:1})}
 const valid=Boolean(recipientName.trim()&&department&&lines.length&&lines.every(line=>line.itemId&&line.locationId&&line.quantity>0&&line.quantity<=getLocationQuantity(line.itemId,line.locationId))&&new Set(lines.map(line=>`${line.itemId}:${line.locationId}`)).size===lines.length)
 const submit=async()=>{if(!valid||saving)return;setSaving(true);try{await create({recipientName:recipientName.trim(),department,note:note.trim(),lines:lines.map(({itemId,locationId,quantity})=>({itemId,locationId,quantity}))});setLines([blankLine()]);setNote('');flash('ส่งคำขอเบิกให้เจ้าหน้าที่แล้ว')}catch(error){flash(error instanceof Error?error.message:'ส่งคำขอไม่สำเร็จ')}finally{setSaving(false)}}
 const approve=async()=>{if(!approveRequest||saving)return;setSaving(true);try{await review(approveRequest.id,'APPROVED');setApproveRequest(null);flash('อนุมัติและตัดสต็อกเรียบร้อย')}catch(error){setApproveRequest(null);flash(error instanceof Error?error.message:'อนุมัติไม่สำเร็จ')}finally{setSaving(false)}}
 const reject=async()=>{if(!rejectRequest||!rejectReason.trim()||saving)return;setSaving(true);try{await review(rejectRequest.id,'REJECTED',rejectReason.trim());setRejectRequest(null);setRejectReason('');flash('บันทึกการไม่อนุมัติแล้ว')}catch(error){flash(error instanceof Error?error.message:'บันทึกไม่สำเร็จ')}finally{setSaving(false)}}
 const requestSummary=useMemo(()=>lines.map(line=>{const item=items.find(row=>row.id===line.itemId);return item?`${item.name} ${line.quantity} ${item.unit}`:''}).filter(Boolean).join(', '),[lines,items])

 if(operator)return <div className="page-stack issue-requests-page"><div className="page-actions"><div><h2>คำขอเบิกที่รออนุมัติ</h2><p className="page-intro">ตรวจสอบรายการก่อนอนุมัติ ระบบจะตัดสต็อกเมื่ออนุมัติสำเร็จเท่านั้น</p></div><span className="request-count-badge">{pending.length} รายการรอ</span></div>{loading&&!requests.length?<div className="card empty">กำลังโหลดคำขอ...</div>:pending.length?pending.map(request=><RequestCard key={request.id} request={request} operator onApprove={setApproveRequest} onReject={request=>{setRejectRequest(request);setRejectReason('')}}/>):<section className="card"><Empty text="ไม่มีคำขอที่รออนุมัติ"/></section>}<div className="section-heading"><h2>ประวัติการพิจารณา</h2><span>{history.length} รายการ</span></div>{history.length?history.map(request=><RequestCard key={request.id} request={request} operator/>):<section className="card"><Empty text="ยังไม่มีประวัติคำขอเบิก"/></section>}{approveRequest&&<Confirm title="ยืนยันอนุมัติคำขอ" detail={`${approveRequest.requestNo} — ระบบจะตัดสต็อก ${approveRequest.lines.length} รายการทันที`} onCancel={()=>setApproveRequest(null)} onConfirm={()=>void approve()}/>} {rejectRequest&&<Modal title="ไม่อนุมัติคำขอ" onClose={()=>setRejectRequest(null)}><div className="modal-body"><label>เหตุผลที่ไม่อนุมัติ *<textarea autoFocus value={rejectReason} onChange={event=>setRejectReason(event.target.value)} placeholder="ระบุเหตุผลเพื่อแจ้งผู้ขอเบิก"/></label></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setRejectRequest(null)}>ยกเลิก</button><button className="btn danger" disabled={!rejectReason.trim()||saving} onClick={()=>void reject()}>ยืนยันไม่อนุมัติ</button></div></Modal>}{toast&&<Toast message={toast}/>}</div>

 if(view==='history')return <div className="page-stack issue-requests-page">
  <div><h2>คำขอของฉัน</h2><p className="page-intro">ติดตามสถานะคำขอเบิกและผลการพิจารณา</p></div>
  {loading&&!requests.length?<div className="card empty">กำลังโหลดคำขอ...</div>:requests.length
   ?requests.map(request=><RequestCard key={request.id} request={request} operator={false} onCancel={async request=>{try{await cancel(request.id);flash('ยกเลิกคำขอแล้ว')}catch(error){flash(error instanceof Error?error.message:'ยกเลิกไม่สำเร็จ')}}}/>)
   :<section className="card"><Empty text="ยังไม่มีคำขอเบิก"/></section>}
  {toast&&<Toast message={toast}/>} 
 </div>

 return <div className="issue-request-create-layout"><section className="card issue-request-form"><div className="stock-title"><div className="red"><PackagePlus/></div><div><h2>ขอเบิกสินค้า</h2><p>ส่งคำขอให้เจ้าหน้าที่ตรวจสอบ โดยยังไม่ตัดสต็อก</p></div></div><div className="form-grid"><label>ผู้รับสินค้า *<input value={recipientName} onChange={event=>setRecipientName(event.target.value)} placeholder="ชื่อ–นามสกุลผู้รับ"/></label><label>แผนก *<select value={department} onChange={event=>setDepartment(event.target.value)}><option value="">เลือกแผนก</option>{DEPARTMENTS.map(value=><option key={value} value={value}>{value}</option>)}</select></label></div><div className="issue-lines-heading"><div><h3>รายการสินค้า</h3><p>เพิ่มได้หลายรายการในคำขอเดียว</p></div><button className="btn compact secondary" onClick={()=>setLines(current=>[...current,blankLine()])}><Plus size={16}/>เพิ่มรายการ</button></div><div className="issue-line-list">{lines.map((line,index)=>{const item=items.find(row=>row.id===line.itemId);const available=getLocationQuantity(line.itemId,line.locationId);return <div className="issue-line" key={line.key}><span className="issue-line-number">{index+1}</span><label>สินค้า<select value={line.itemId} onChange={event=>selectItem(line,event.target.value)}><option value="">เลือกสินค้า</option>{activeItems.map(row=><option key={row.id} value={row.id}>{row.sku} — {row.name}</option>)}</select></label><label>จำนวน<input type="number" min="0.01" step="0.01" max={available||undefined} value={line.quantity||''} onChange={event=>updateLine(line.key,{quantity:Number(event.target.value)})}/><small>คงเหลือ {available} {item?.unit??''}</small></label><button className="icon-btn issue-line-remove" aria-label="ลบรายการ" disabled={lines.length===1} onClick={()=>setLines(current=>current.filter(row=>row.key!==line.key))}><Trash2 size={18}/></button></div>})}</div>{!activeItems.length&&<p className="form-error">ยังไม่มีสินค้าที่มียอดคงเหลือ กรุณาติดต่อเจ้าหน้าที่พัสดุ</p>}<label>หมายเหตุ<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="รายละเอียดเพิ่มเติม (ถ้ามี)"/></label><button className="btn primary submit-btn" disabled={!valid||saving} onClick={()=>void submit()}><Send size={18}/>{saving?'กำลังส่ง...':'ส่งคำขอเบิก'}</button></section><aside className="stock-preview issue-request-preview"><span>สรุปคำขอ</span><strong>{lines.filter(line=>line.itemId).length} รายการ</strong><p>{requestSummary||'เลือกรายการสินค้าที่ต้องการเบิก'}</p><div className="safety-note"><Clock3 size={18}/>สต็อกจะยังไม่เปลี่ยนจนกว่าเจ้าหน้าที่จะกดอนุมัติ</div></aside>{toast&&<Toast message={toast}/>}</div>
}
