import { ArrowDownToLine, ArrowLeft, ArrowRightLeft, ArrowUpFromLine, Edit3, Package, SlidersHorizontal } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Empty, StatusBadge, TxBadge } from '../components/ui'
import { useStock } from '../store/StockContext'
import { useAuth } from '../store/AuthContext'
import { formatThaiDateTime } from '../utils/date'

export function ItemDetailPage(){
 const {id}=useParams();const nav=useNavigate();const {user}=useAuth();const {items,categories,locations,transactions,getLocationQuantity}=useStock();const item=items.find(row=>row.id===id)
 if(!item)return <Empty text="ไม่พบสินค้านี้"/>
 const history=transactions.filter(transaction=>transaction.itemId===item.id)
 return <div className="page-stack"><button className="back-link" onClick={()=>nav(-1)}><ArrowLeft size={18}/>กลับไปคลังสินค้า</button>
  <section className="detail-hero"><div className="detail-image"><Package size={54}/></div><div className="detail-main"><span className="mono">{item.sku}</span><h2>{item.name}</h2><p>{item.description}</p><div className="detail-tags"><StatusBadge item={item}/><span>{categories.find(category=>category.id===item.categoryId)?.name}</span></div></div><div className="detail-stock"><span>สต็อกรวมปัจจุบัน</span><strong>{item.quantity}</strong><small>{item.unit}</small></div>{user?.role!=='viewer'&&<div className="detail-buttons"><Link className="btn primary" to={`/stock-in?item=${item.id}`}><ArrowDownToLine size={18}/>รับเข้า</Link><Link className="btn danger" to={`/stock-out?item=${item.id}`}><ArrowUpFromLine size={18}/>เบิกออก</Link><Link className="btn secondary" to={`/stock-transfer?item=${item.id}`}><ArrowRightLeft size={18}/>โอนย้าย</Link><Link className="btn secondary" to={`/stock-adjust?item=${item.id}`}><SlidersHorizontal size={18}/>ปรับยอด</Link><Link className="btn secondary" to="/inventory"><Edit3 size={18}/>แก้ไข</Link></div>}</section>
  <section className="detail-grid"><div className="card"><div className="card-head"><h2>ข้อมูลสินค้า</h2></div><dl className="info-list"><div><dt>หมวดหมู่</dt><dd>{categories.find(category=>category.id===item.categoryId)?.name}</dd></div><div><dt>ตำแหน่งหลัก</dt><dd>{locations.find(location=>location.id===item.locationId)?.name}</dd></div><div><dt>สต็อกขั้นต่ำ</dt><dd>{item.minStock} {item.unit}</dd></div><div><dt>หน่วยนับ</dt><dd>{item.unit}</dd></div><div><dt>บาร์โค้ด</dt><dd className="mono">{item.barcode||'—'}</dd></div><div><dt>วันที่สร้าง</dt><dd>{new Intl.DateTimeFormat('th-TH',{dateStyle:'long'}).format(new Date(item.createdAt))}</dd></div></dl><div className="balance-breakdown"><h3>ยอดแยกตามตำแหน่ง</h3>{locations.map(location=><div key={location.id}><span>{location.name}</span><b>{getLocationQuantity(item.id,location.id)} {item.unit}</b></div>)}</div></div>
   <div className="card span-2"><div className="card-head"><div><h2>ประวัติการเคลื่อนไหว</h2><p>รายการล่าสุดของสินค้านี้</p></div></div><div className="table-wrap"><table><thead><tr><th>วันและเวลา</th><th>รายการ</th><th>ตำแหน่ง</th><th>ก่อนหน้า</th><th>จำนวน</th><th>คงเหลือ</th><th>ผู้ดำเนินการ</th></tr></thead><tbody>{history.map(transaction=>{const source=locations.find(location=>location.id===transaction.locationId)?.name;const destination=locations.find(location=>location.id===transaction.destinationLocationId)?.name;return <tr key={transaction.id}><td>{formatThaiDateTime(transaction.createdAt)}</td><td><TxBadge type={transaction.type}/></td><td>{transaction.type==='TRANSFER'?`${source} → ${destination}`:source}</td><td>{transaction.before}</td><td>{transaction.quantity}</td><td><b>{transaction.after}</b></td><td>{transaction.user}</td></tr>})}</tbody></table>{!history.length&&<Empty text="ยังไม่มีประวัติของสินค้านี้"/>}</div></div>
  </section>
 </div>
}
