import { MapPin, Plus, Tags, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Modal, Toast } from '../components/ui'
import { useStock } from '../store/StockContext'
import { useAuth } from '../store/AuthContext'

function MasterPage({kind}:{kind:'category'|'location'}){const store=useStock();const {user}=useAuth();const isCat=kind==='category';const data=isCat?store.categories:store.locations;const [open,setOpen]=useState(false);const [name,setName]=useState('');const [desc,setDesc]=useState('');const [toast,setToast]=useState('');const [saving,setSaving]=useState(false);const Icon=isCat?Tags:MapPin;const canDelete=user?.role==='admin'
 const save=async()=>{if(!name.trim()||saving)return;setSaving(true);try{if(isCat)await store.addCategory(name.trim(),desc.trim());else await store.addLocation(name.trim(),desc.trim());setOpen(false);setName('');setDesc('');setToast('บันทึกข้อมูลเรียบร้อย')}catch(error){setToast(error instanceof Error?error.message:'บันทึกข้อมูลไม่สำเร็จ')}finally{setSaving(false);setTimeout(()=>setToast(''),2500)}}
 return <div className="page-stack"><div className="page-actions"><p className="page-intro">{isCat?'จัดกลุ่มสินค้าเพื่อค้นหาและสรุปรายงานได้ง่ายขึ้น':'กำหนดห้อง คลัง หรือตำแหน่งที่ใช้จัดเก็บสินค้า'}</p><button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>{isCat?'เพิ่มหมวดหมู่':'เพิ่มตำแหน่ง'}</button></div><section className="master-grid">{data.map(x=>{const count=isCat?store.items.filter(i=>i.categoryId===x.id).length:store.items.filter(i=>i.locationId===x.id).length;return <article className="master-card" key={x.id}><div className="master-icon"><Icon/></div><div><h3>{x.name}</h3><p>{x.description}</p><span>{count} รายการสินค้า</span></div>{canDelete&&<button className="icon-btn danger-text" disabled={count>0} title={count>0?'ยังมีสินค้าในรายการนี้':'ลบ'} onClick={()=>isCat?store.deleteCategory(x.id):store.deleteLocation(x.id)}><Trash2 size={18}/></button>}</article>})}</section>{open&&<Modal title={isCat?'เพิ่มหมวดหมู่':'เพิ่มตำแหน่งจัดเก็บ'} onClose={()=>setOpen(false)}><div className="modal-body form-stack"><label>{isCat?'ชื่อหมวดหมู่':'ชื่อตำแหน่ง'} *<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><label>คำอธิบาย<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label></div><div className="modal-actions"><button className="btn secondary" disabled={saving} onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={!name.trim()||saving} onClick={()=>void save()}>{saving?'กำลังบันทึก...':'บันทึก'}</button></div></Modal>}{toast&&<Toast message={toast}/>}</div>}
export const CategoriesPage=()=> <MasterPage kind="category"/>;export const LocationsPage=()=> <MasterPage kind="location"/>
