import { MapPin, Plus, Tags, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Modal, Toast } from '../components/ui'
import { useStock } from '../store/StockContext'

function MasterPage({kind}:{kind:'category'|'location'}){const store=useStock();const isCat=kind==='category';const data=isCat?store.categories:store.locations;const [open,setOpen]=useState(false);const [name,setName]=useState('');const [desc,setDesc]=useState('');const [toast,setToast]=useState('');const Icon=isCat?Tags:MapPin
 const save=()=>{if(!name)return;isCat?store.addCategory(name,desc):store.addLocation(name,desc);setOpen(false);setName('');setDesc('');setToast('บันทึกข้อมูลเรียบร้อย');setTimeout(()=>setToast(''),2500)}
 return <div className="page-stack"><div className="page-actions"><p className="page-intro">{isCat?'จัดกลุ่มสินค้าเพื่อค้นหาและสรุปรายงานได้ง่ายขึ้น':'กำหนดห้อง คลัง หรือตำแหน่งที่ใช้จัดเก็บสินค้า'}</p><button className="btn primary" onClick={()=>setOpen(true)}><Plus size={18}/>{isCat?'เพิ่มหมวดหมู่':'เพิ่มตำแหน่ง'}</button></div><section className="master-grid">{data.map(x=>{const count=isCat?store.items.filter(i=>i.categoryId===x.id).length:store.items.filter(i=>i.locationId===x.id).length;return <article className="master-card" key={x.id}><div className="master-icon"><Icon/></div><div><h3>{x.name}</h3><p>{x.description}</p><span>{count} รายการสินค้า</span></div><button className="icon-btn danger-text" disabled={count>0} title={count>0?'ยังมีสินค้าในรายการนี้':'ลบ'} onClick={()=>isCat?store.deleteCategory(x.id):store.deleteLocation(x.id)}><Trash2 size={18}/></button></article>})}</section>{open&&<Modal title={isCat?'เพิ่มหมวดหมู่':'เพิ่มตำแหน่งจัดเก็บ'} onClose={()=>setOpen(false)}><div className="modal-body form-stack"><label>{isCat?'ชื่อหมวดหมู่':'ชื่อตำแหน่ง'} *<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><label>คำอธิบาย<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={!name} onClick={save}>บันทึก</button></div></Modal>}{toast&&<Toast message={toast}/>}</div>}
export const CategoriesPage=()=> <MasterPage kind="category"/>;export const LocationsPage=()=> <MasterPage kind="location"/>
