import { ArrowRight, ArrowRightLeft, CheckCircle2, SlidersHorizontal } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Confirm, Toast } from '../components/ui'
import { useStock } from '../store/StockContext'

export function StockControlPage({mode}:{mode:'ADJUST'|'TRANSFER'}){
 const {items,locations,getLocationQuantity,adjustStock,transferStock}=useStock();const [params]=useSearchParams()
 const [itemId,setItemId]=useState(params.get('item')??items[0]?.id??'');const item=items.find(row=>row.id===itemId)
 const availableLocations=useMemo(()=>locations.filter(location=>getLocationQuantity(itemId,location.id)>0),[locations,itemId,getLocationQuantity])
 const [sourceLocationId,setSourceLocationId]=useState(item?.locationId??locations[0]?.id??'')
 const [destinationLocationId,setDestinationLocationId]=useState(locations.find(location=>location.id!==sourceLocationId)?.id??'')
 const [countedQuantity,setCountedQuantity]=useState(0);const [quantity,setQuantity]=useState(1)
 const [referenceNo,setReferenceNo]=useState('');const [reason,setReason]=useState('');const [note,setNote]=useState('')
 const [confirm,setConfirm]=useState(false);const [saving,setSaving]=useState(false);const [toast,setToast]=useState('');const [error,setError]=useState('')
 const before=getLocationQuantity(itemId,sourceLocationId);const difference=countedQuantity-before
 useEffect(()=>{const preferred=locations.find(location=>getLocationQuantity(itemId,location.id)>0)?.id??item?.locationId??locations[0]?.id??'';setSourceLocationId(preferred)},[itemId,item,locations,getLocationQuantity])
 useEffect(()=>{setCountedQuantity(getLocationQuantity(itemId,sourceLocationId));if(destinationLocationId===sourceLocationId)setDestinationLocationId(locations.find(location=>location.id!==sourceLocationId)?.id??'')},[itemId,sourceLocationId,destinationLocationId,locations,getLocationQuantity])
 const valid=mode==='ADJUST'?Boolean(item&&sourceLocationId&&countedQuantity>=0&&countedQuantity!==before&&referenceNo.trim()&&reason.trim()):Boolean(item&&sourceLocationId&&destinationLocationId&&sourceLocationId!==destinationLocationId&&quantity>0&&quantity<=before&&referenceNo.trim()&&reason.trim())
 const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2800)}
 const save=async()=>{if(saving||!valid)return;setSaving(true);try{if(mode==='ADJUST')await adjustStock({itemId,locationId:sourceLocationId,countedQuantity,referenceNo:referenceNo.trim(),reason:reason.trim(),note});else await transferStock({itemId,sourceLocationId,destinationLocationId,quantity,referenceNo:referenceNo.trim(),reason:reason.trim(),note});setConfirm(false);setError('');setReferenceNo('');setReason('');setNote('');setQuantity(1);flash(mode==='ADJUST'?'ปรับยอดสต็อกเรียบร้อย':'โอนย้ายสต็อกเรียบร้อย')}catch(problem){setConfirm(false);setError(problem instanceof Error?problem.message:'บันทึกรายการไม่สำเร็จ')}finally{setSaving(false)}}
 const sourceName=locations.find(location=>location.id===sourceLocationId)?.name;const destinationName=locations.find(location=>location.id===destinationLocationId)?.name
 return <div className="stock-page"><section className="card stock-form"><div className="stock-title"><div className={mode==='ADJUST'?'amber':'blue'}>{mode==='ADJUST'?<SlidersHorizontal/>:<ArrowRightLeft/>}</div><div><h2>{mode==='ADJUST'?'ปรับยอดจากการตรวจนับ':'โอนย้ายตำแหน่งจัดเก็บ'}</h2><p>{mode==='ADJUST'?'แก้ไขยอดเมื่อจำนวนที่ตรวจนับจริงไม่ตรงกับระบบ':'ย้ายสต็อกระหว่างตำแหน่งโดยยอดรวมสินค้าไม่เปลี่ยน'}</p></div></div><div className="form-stack">
  <label>สินค้า *<select value={itemId} onChange={event=>setItemId(event.target.value)}>{items.filter(row=>row.isActive).map(row=><option value={row.id} key={row.id}>{row.sku} — {row.name}</option>)}</select></label>
  <div className="location-balance-list">{locations.map(location=><span key={location.id} className={location.id===sourceLocationId?'active':''}>{location.name}<b>{getLocationQuantity(itemId,location.id)} {item?.unit}</b></span>)}</div>
  <div className="form-grid"><label>{mode==='ADJUST'?'ตำแหน่งที่ตรวจนับ':'ตำแหน่งต้นทาง'} *<select value={sourceLocationId} onChange={event=>setSourceLocationId(event.target.value)}>{(mode==='TRANSFER'?availableLocations:locations).map(location=><option value={location.id} key={location.id}>{location.name}</option>)}</select></label>
   {mode==='ADJUST'?<label>ยอดตรวจนับจริง *<input type="number" min="0" value={countedQuantity} onChange={event=>setCountedQuantity(Number(event.target.value))}/></label>:<><label>ตำแหน่งปลายทาง *<select value={destinationLocationId} onChange={event=>setDestinationLocationId(event.target.value)}>{locations.filter(location=>location.id!==sourceLocationId).map(location=><option value={location.id} key={location.id}>{location.name}</option>)}</select></label><label>จำนวนที่โอน *<input type="number" min="1" max={before} value={quantity} onChange={event=>setQuantity(Number(event.target.value))}/></label></>}
   <label>เลขที่อ้างอิง *<input value={referenceNo} onChange={event=>setReferenceNo(event.target.value)} placeholder={mode==='ADJUST'?'เช่น COUNT-2609-001':'เช่น TR-2609-001'}/></label><label className={mode==='ADJUST'?'full':''}>เหตุผล *<input value={reason} onChange={event=>setReason(event.target.value)} placeholder={mode==='ADJUST'?'เช่น ตรวจนับประจำเดือน':'เช่น ย้ายไปคลังฝ่ายธุรการ'}/></label>
  </div><label>หมายเหตุ<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="รายละเอียดเพิ่มเติม (ถ้ามี)"/></label>{error&&<p className="form-error">{error}</p>}<button className="btn primary submit-btn" disabled={!valid||saving} onClick={()=>setConfirm(true)}>{saving?'กำลังบันทึก...':'ตรวจสอบและยืนยัน'}</button>
 </div></section>
 <aside className="stock-preview"><span>สรุปรายการ</span><div className="preview-item"><div className="product-icon">{item?.name.charAt(0)}</div><div><b>{item?.name}</b><small>{item?.sku} · ยอดรวม {item?.quantity??0} {item?.unit}</small></div></div>{mode==='ADJUST'?<><div className="stock-math"><div><span>ยอดในระบบ</span><strong>{before} <small>{item?.unit}</small></strong></div><ArrowRight/><div><span>ยอดตรวจนับ</span><strong>{countedQuantity} <small>{item?.unit}</small></strong></div></div><div className={`change-box ${difference>=0?'in':'out'}`}><span>ผลต่าง</span><b>{difference>=0?'+':''}{difference} {item?.unit}</b></div></>:<><div className="transfer-preview"><div><span>ต้นทาง</span><b>{sourceName}</b><strong>{before} → {Math.max(0,before-quantity)} {item?.unit}</strong></div><ArrowRight/><div><span>ปลายทาง</span><b>{destinationName}</b><strong>{getLocationQuantity(itemId,destinationLocationId)} → {getLocationQuantity(itemId,destinationLocationId)+quantity} {item?.unit}</strong></div></div><div className="change-box in"><span>ยอดรวมหลังโอน</span><b>{item?.quantity??0} {item?.unit}</b></div></>}<div className="safety-note"><CheckCircle2 size={18}/>ระบบบันทึกยอดก่อนและหลัง เลขอ้างอิง เหตุผล และผู้ดำเนินการ เพื่อตรวจสอบย้อนหลัง</div></aside>
 {confirm&&<Confirm title={mode==='ADJUST'?'ยืนยันการปรับยอดสต็อก':'ยืนยันการโอนย้ายสต็อก'} detail={mode==='ADJUST'?`${item?.name} ที่ ${sourceName}: ${before} เป็น ${countedQuantity} ${item?.unit}`:`โอน ${item?.name} จำนวน ${quantity} ${item?.unit} จาก ${sourceName} ไป ${destinationName} โดยยอดรวมไม่เปลี่ยน`} onCancel={()=>setConfirm(false)} onConfirm={save}/>} {toast&&<Toast message={toast}/>}
 </div>
}
