import { ArrowDownToLine, ArrowRight, ArrowUpFromLine, CheckCircle2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Confirm, Toast } from '../components/ui'
import { useStock } from '../store/StockContext'

export function StockFormPage({mode}:{mode:'IN'|'OUT'}){const {items,locations,applyStock}=useStock();const [params]=useSearchParams();const [itemId,setItemId]=useState(params.get('item')??items[0]?.id??'');const item=items.find(i=>i.id===itemId);const [qty,setQty]=useState(1);const [locationId,setLocationId]=useState(item?.locationId??locations[0]?.id??'');const [referenceNo,setReferenceNo]=useState('');const [employeeName,setEmployeeName]=useState('');const [department,setDepartment]=useState('');const [purpose,setPurpose]=useState('');const [note,setNote]=useState('');const [confirm,setConfirm]=useState(false);const [toast,setToast]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(item)setLocationId(item.locationId)},[item]);const after=item?(mode==='IN'?item.quantity+qty:item.quantity-qty):0;const valid=Boolean(item&&qty>0&&locationId&&(mode==='IN'||(employeeName&&department&&purpose))&&after>=0)
 const save=async()=>{try{await applyStock(mode,{itemId,locationId,quantity:qty,referenceNo,employeeName,department,purpose,note});setConfirm(false);setToast(mode==='IN'?'รับสินค้าเข้าสต็อกเรียบร้อย':'บันทึกการเบิกสินค้าเรียบร้อย');setError('');setQty(1);setTimeout(()=>setToast(''),3000)}catch(e){setConfirm(false);setError(e instanceof Error?e.message:'เกิดข้อผิดพลาด')}}
 return <div className="stock-page"><section className="card stock-form"><div className="stock-title"><div className={mode==='IN'?'green':'red'}>{mode==='IN'?<ArrowDownToLine/>:<ArrowUpFromLine/>}</div><div><h2>{mode==='IN'?'รับสินค้าเข้าสต็อก':'เบิกสินค้าออกจากสต็อก'}</h2><p>{mode==='IN'?'บันทึกสินค้าที่รับเข้าคลัง':'บันทึกการจ่ายวัสดุให้พนักงาน'}</p></div></div><div className="form-stack"><label>สินค้า *<select value={itemId} onChange={e=>setItemId(e.target.value)}>{items.filter(i=>i.isActive).map(i=><option value={i.id} key={i.id}>{i.sku} — {i.name}</option>)}</select></label><div className="form-grid"><label>ตำแหน่งจัดเก็บ *<select value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label>จำนวน *<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>{mode==='IN'?<><label>เลขที่อ้างอิง<input value={referenceNo} onChange={e=>setReferenceNo(e.target.value)} placeholder="เช่น PO-2609-025"/></label><label>ผู้จำหน่าย<input placeholder="ชื่อบริษัทหรือร้านค้า"/></label></>:<><label>ชื่อพนักงาน *<input value={employeeName} onChange={e=>setEmployeeName(e.target.value)} placeholder="ผู้ขอเบิก"/></label><label>แผนก *<input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="เช่น ฝ่ายบัญชี"/></label><label className="full">วัตถุประสงค์ *<input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="ระบุการนำไปใช้งาน"/></label></>}</div><label>หมายเหตุ<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="รายละเอียดเพิ่มเติม (ถ้ามี)"/></label>{error&&<p className="form-error">{error}</p>}<button className={`btn ${mode==='IN'?'primary':'danger'} submit-btn`} disabled={!valid} onClick={()=>setConfirm(true)}>ตรวจสอบและยืนยัน</button></div></section>
 <aside className="stock-preview"><span>สรุปรายการ</span><div className="preview-item"><div className="product-icon">{item?.name.charAt(0)}</div><div><b>{item?.name}</b><small>{item?.sku}</small></div></div><div className="stock-math"><div><span>{mode==='IN'?'สต็อกปัจจุบัน':'สต็อกที่พร้อมเบิก'}</span><strong>{item?.quantity??0} <small>{item?.unit}</small></strong></div><ArrowRight/><div><span>{mode==='IN'?'สต็อกใหม่':'คงเหลือหลังเบิก'}</span><strong className={after<0?'negative':'positive'}>{after} <small>{item?.unit}</small></strong></div></div><div className={`change-box ${mode==='IN'?'in':'out'}`}><span>{mode==='IN'?'จำนวนรับเข้า':'จำนวนที่เบิก'}</span><b>{mode==='IN'?'+':'−'}{qty} {item?.unit}</b></div>{after<0&&<p className="form-error">จำนวนที่ขอเบิกมากกว่าสต็อกคงเหลือ</p>}<div className="safety-note"><CheckCircle2 size={18}/>ระบบจะบันทึกยอดก่อนและหลังทุกครั้ง เพื่อให้ตรวจสอบย้อนหลังได้</div></aside>
 {confirm&&<Confirm title={mode==='IN'?'ยืนยันการรับสินค้า':'ยืนยันการเบิกสินค้า'} detail={`${item?.name} จำนวน ${qty} ${item?.unit} — คงเหลือหลังรายการ ${after} ${item?.unit}`} onCancel={()=>setConfirm(false)} onConfirm={save}/>} {toast&&<Toast message={toast}/>}</div>}
